# Hacktiv8 Python for Data Science

Topic of discussion
- Numpy

## Creating Array
- np.array() #untuk membuat array NumPy
- np.zeros() #create an array filled with 0s
- np.ones() #create an array filled with 1s
- np.empty() #create an array whose initial content is random
- np.arange() #create an array with a range of elements

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [5]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
print(np.arange(5))
print(np.arange(0, 20, 2)) #start, stop, step

[0 1 2 3 4]
[ 0  2  4  6  8 10 12 14 16 18]


## Add, Remove, and Sort
- np.append() #menambahkan element
- np.delete() #menghapus element
- np.sort() #mengurutkan element

In [7]:
arr = np.array([2, 3, 4, 5, 6, 7])
np.append(arr, [9, 8])

array([2, 3, 4, 5, 6, 7, 9, 8])

In [8]:
np.delete(arr, 2)

array([2, 3, 5, 6, 7])

In [9]:
arr1 = np.array([3, 7, 1, 0, 5, 8, 2])
np.sort(arr1)

array([0, 1, 2, 3, 5, 7, 8])

## Shape and Size
- ndarray.ndim() #untuk menentukan jumlah axes atau dimensi dari array.
- ndarray.size() #untuk menentukan jumlah total element array
- ndarray.shape() #untuk menampilkan tuple int yang menunjukkan jumlah element yang disimpan
- np.reshape() #unruk memberikan bentuk baru ke array tanpa mengubah datanya.

In [10]:
array_example = np.array([[[0, 1, 2, 3], [4, 5, 6, 7]], 
                            [[0, 1, 2, 3], [4, 5, 6, 7]],
                            [[0, 1, 2, 3], [4, 5, 6, 7]]])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [11]:
array_example.ndim

3

In [22]:
array_example.size

24

In [12]:
array_example.shape

(3, 2, 4)

In [13]:
q = np.arange(6)
print(q)

[0 1 2 3 4 5]


In [14]:
w = q.reshape(2, 3)
print(w)

[[0 1 2]
 [3 4 5]]


In [15]:
q.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Convert 1D to 2D

In [16]:
q = np.array([1, 2, 3, 4, 5, 6])
q.shape

(6,)

In [17]:
#you can use np.newaxis to add a new axis
q2 = q[np.newaxis]
print(q2.shape)
print(q2)

(1, 6)
[[1 2 3 4 5 6]]


In [18]:
# You can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 3)
[[1 2 3]]


In [19]:
# for a column vector, You can insert an axis along the second dimension

col_vector = q[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [20]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [21]:
# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [22]:
# You can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

## Indexing dan Slicing

In [23]:
data = np.array([1,2,3])

In [24]:
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [25]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
# You can easily print all of the values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [27]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [28]:
# You can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [29]:
# you can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


## Creating Array from Existing Data
- slicing indexing
- np.vstack()
- np.hstack()
- np.hsplit()
- .view()
- .copy()

In [45]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
print(arr)
arr1 = arr[3:8]
arr1

[ 1  2  3  4  5  6  7  8  9 10]


array([4, 5, 6, 7, 8])

In [46]:
#menumpuk array secara vertikal dengan vstack
a_1 = np.array([[1, 1],
                [2, 2]])

a_2 = np.array([[3, 3],
                [4, 4]])   
                
np.vstack((a_1, a_2))             

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [47]:
# Or stack them horizontally with hstack
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [48]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [49]:
# If you wanted to split this array into three equally shaped arrays

np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [50]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
# You can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
# Using the copy method will make a complete copy of the array and its data (a deep copy).

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic array operations

In [53]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [54]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [55]:
# You can sum the rows

b.sum(axis=0)

array([3, 3])

In [56]:
# You can sum the columns

b.sum(axis=1)

array([2, 4])

In [57]:
data = np.array([1, 2])
data

array([1, 2])

In [58]:
ones = np.ones(2)
ones

array([1., 1.])

In [59]:
data + ones

array([2., 3.])

In [60]:
data * data

array([1, 4])

In [61]:
data / data

array([1., 1.])

## Broadcasting
mekanisme yang memungkinkan NumPy melakukan operasi pada array dengan bentuk berbeda

In [62]:
data * 2

array([2, 4])

In [ ]:
data.max()
data.min()
data.sum()

In [63]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [67]:
print(A.sum())
print(A.min())
print(A.min(axis=0))
print(A.max())
print(A.max(axis=1))
print(A.std())

4.8595784
0.05093587
[0.12697628 0.05093587 0.26590556 0.5510652 ]
0.82485143
[0.5510652  0.55645993 0.82485143]
0.21392120766089617


## Matrices

In [68]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.63961199 0.43240609]
 [0.92886845 0.39282553]
 [0.94818482 0.58049338]]


### Matrix Arithmetric

In [69]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [70]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [71]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [72]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [73]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


### Dot Product

In [74]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [75]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

### Matrix Indexing

In [76]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


### Matrix Aggregation

In [77]:
print(data)
print(data.max())
print(data.min())
print(data.sum())

[[1 2]
 [3 4]
 [5 6]]
6
1
21


In [78]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


### Transposing and Reshaping

In [79]:
print(data)
print(data.T)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [80]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [81]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [83]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


### N-Dimensional Array

In [84]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [85]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [86]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [87]:
print(np.random.random((4,3,2)))

[[[0.77850034 0.16268266]
  [0.36509449 0.12264939]
  [0.31942812 0.95364325]]

 [[0.68577909 0.74825358]
  [0.33250528 0.73891473]
  [0.83415794 0.67143312]]

 [[0.14171068 0.71207851]
  [0.04461809 0.98139289]
  [0.68430532 0.6708607 ]]

 [[0.11578555 0.99474014]
  [0.3657766  0.80184178]
  [0.2248036  0.19359973]]]


### Flatten N-Dimensional Array

In [88]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [89]:
# You can use flatten to flatten your array into a 1D array.

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])